base/urls.py
from django.urls import path
from .views import TaskList, TaskDetail, TaskCreate, TaskUpdate, DeleteView, CustomLoginView, RegisterPage, themeChangeView, toggleHideCompleted, toggleTaskCompleted, contrastChangeView, toggleFilterByDeadline, UserSettingssUpdate, readmeView
from django.contrib.auth.views import LogoutView

urlpatterns = [
  path('login/', CustomLoginView.as_view(), name='login'),
  path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
  path('register/', RegisterPage.as_view(), name='register'),


  path('', TaskList.as_view(), name='tasks'),
  path('task/<int:pk>/', TaskDetail.as_view(), name='task'),
  path('task-create/', TaskCreate.as_view(), name='task-create'),
  path('task-update/<int:pk>/', TaskUpdate.as_view(), name='task-update'),
  path('task-delete/<int:pk>/', DeleteView.as_view(), name='task-delete'),
  path('task-toggle-status/', toggleTaskCompleted, name='task-toggle-status'),

  path('changetheme/', themeChangeView, name='theme'),
  path('changecontrast/', contrastChangeView, name='contrast'),
  path('hide_completed/', toggleHideCompleted, name='hide_completed'),
  path('filter_by_deadline/', toggleFilterByDeadline, name='filter_by_deadline'),
  path('users_display_after_date/<int:pk>/', UserSettingssUpdate.as_view(), name='users_display_after_date'),
  

  path('readme', readmeView, name='readme')
]

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('base.urls')),
]

base/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import *
from django.utils import timezone
# Create your models here.

class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    complete = models.BooleanField(default=False)
    deadline = models.DateField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['complete', '-deadline', 'created']


class UsersSettings(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False, blank=False)
    darkmode = models.BooleanField(default=True)
    hide_completed = models.BooleanField(default=False)
    high_contrast = models.BooleanField(default=True)
    filter_by_deadline = models.BooleanField(default=True)
    users_display_after_date = models.DateTimeField(default = timezone.now)

base/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.urls import reverse_lazy

from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login  

from .models import Task, UsersSettings
from django.core.exceptions import PermissionDenied

def apply_settings(self, context):
  context['users_settings'] = UsersSettings.objects.filter(user=self.request.user)[0]
  return context

class CustomLoginView(LoginView):
  template_name = 'base/login.html'
  fields = '__all__'
  redirect_authenticated_user = True

  def get_success_url(self):
    return reverse_lazy('tasks')

class RegisterPage(FormView):
  template_name = 'base/register.html'
  form_class = UserCreationForm
  redirect_authenticated_user = True
  success_url = reverse_lazy('tasks')

  def form_invalid(self, form):
    return super().form_invalid(form)

  def form_valid(self, form):
    user = form.save()
    if user is not None:
      new_users_settings = UsersSettings(user=user)
      new_users_settings.save()
      login(self.request, user)
    return super(RegisterPage, self).form_valid(form)
  
  def get(self, *args, **kwargs):
    if self.request.user.is_authenticated:
      return redirect('tasks')
    return super(RegisterPage, self).get(*args, **kwargs) 


class TaskList(LoginRequiredMixin, ListView):
  model = Task
  context_object_name = 'tasks'

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context['tasks'] = context['tasks'].filter(user=self.request.user)

    display_after_date = "1901-01-01" #"2000-12-31"
    settings = UsersSettings.objects.filter(user=self.request.user)[0]
    users_display_after_date = settings.users_display_after_date
    filter_by_deadline = settings.filter_by_deadline

    if filter_by_deadline and users_display_after_date:
      display_after_date = users_display_after_date

    deadline_after_date = context['tasks'].filter(deadline__gte=display_after_date)
    without_deadline = context['tasks'].filter(deadline=None)
    context['tasks'] = deadline_after_date | without_deadline

    search_input = self.request.GET.get("search-area") or ''
    if search_input:
      context['tasks'] = context['tasks'].filter(title__icontains=search_input)

    context['count'] = context['tasks'].filter(complete=False).count()
    context['totalcount'] = context['tasks'].count()
    context['search_input'] = search_input

    context['display_settings'] = True
    return apply_settings(self, context)

class TaskDetail(LoginRequiredMixin, DetailView):
  model = Task
  context_object_name = 'task'
  template_name = 'base/task.html'

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    if context.task.user != self.request.user:
      raise PermissionDenied()
    return apply_settings(self, context)

class TaskCreate(LoginRequiredMixin, CreateView):
  model = Task
  fields = ['title', 'description', 'complete', 'deadline']
  success_url = reverse_lazy('tasks')

  def form_valid(self, form):
    form.instance.user = self.request.user
    return super(TaskCreate, self).form_valid(form)

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    return apply_settings(self, context)

class TaskUpdate(LoginRequiredMixin, UpdateView):
  model = Task
  fields = ['title', 'description', 'complete', 'deadline']
  success_url = reverse_lazy('tasks')

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    if context['task'].deadline:
      context['task'].deadline = context['task'].deadline.strftime("%Y-%m-%d")
    if context["task"].user != self.request.user:
      raise PermissionDenied()
    return apply_settings(self, context)

class UserSettingssUpdate(LoginRequiredMixin, UpdateView):
  model = UsersSettings
  fields = ['users_display_after_date']
  success_url = reverse_lazy('tasks')

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    if context['userssettings'].users_display_after_date:
      context['userssettings'].users_display_after_date = context['userssettings'].users_display_after_date.strftime("%Y-%m-%d")
    if context["userssettings"].user != self.request.user:
      raise PermissionDenied()
    return apply_settings(self, context)

class DeleteView(LoginRequiredMixin, DeleteView):
  model = Task
  context_object_name = 'task'
  success_url = reverse_lazy('tasks')

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    if context['task'].user != self.request.user:
      raise PermissionDenied()
    return apply_settings(self, context)

def toggleTaskCompleted(request):
  requestedTaskId = request.GET.get('id')
  if Task.objects.filter(user=request.user, id=requestedTaskId).exists():
    task = Task.objects.get(user=request.user, id=requestedTaskId)
    task.complete = not task.complete
    task.save()
  return redirect('tasks')
  
def themeChangeView(request):
  if UsersSettings.objects.filter(user=request.user).exists():
    settings = UsersSettings.objects.get(user=request.user)
    settings.darkmode = not settings.darkmode
    settings.save()
  return redirect('tasks')
  
def contrastChangeView(request):
  if UsersSettings.objects.filter(user=request.user).exists():
    settings = UsersSettings.objects.get(user=request.user)
    settings.high_contrast = not settings.high_contrast
    settings.save()
  return redirect('tasks')
  
def toggleHideCompleted(request):
  if UsersSettings.objects.filter(user=request.user).exists():
    settings = UsersSettings.objects.get(user=request.user)
    settings.hide_completed = not settings.hide_completed
    settings.save()
  return redirect('tasks')
  
def toggleFilterByDeadline(request):
  if UsersSettings.objects.filter(user=request.user).exists():
    settings = UsersSettings.objects.get(user=request.user)
    settings.filter_by_deadline = not settings.filter_by_deadline
    settings.save()
  return redirect('tasks')

def readmeView(request):
  context = {}
  context['hide_footer'] = True
  # context['display_settings'] = True
  if request.user.is_authenticated:
    context['users_settings'] = UsersSettings.objects.filter(user=request.user)[0]
  return render(request, '../templates/base/readme.html', context=context)

base/templates/base/login.html
{% extends 'base/main.html' %}
<!-- displaying the view as content of base/main.html -->
{% block content %}
<!-- content -->

<header>
  <h1>Log in</h1>
</header>

<div class="card-body-as-p text">
  <form method="POST">
    {% csrf_token %} {{form.as_p}}
    <input class="button" type="submit" value="Login" />
  </form>
  <p>
    Don't have an account? <a href="{% url 'register' %}" class="text"><u>Register</u></a>
  </p>
</div>

{% endblock content %}

base/templates/base/main.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>TODO</title>
    <link rel="icon" type="image/png" href="{% static 'base/todofavicon.png' %}" />

    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Lobster&family=Nunito&display=swap" rel="stylesheet" />
    {% if not users_settings %}
    <link rel="stylesheet" href="{% static 'base/darkmode_contrast_vars.css' %}" />
    {% elif users_settings.darkmode and users_settings.high_contrast %}
    <link rel="stylesheet" href="{% static 'base/darkmode_contrast_vars.css' %}" />
    {% elif users_settings.darkmode and not users_setting.high_contrast %}
    <link rel="stylesheet" href="{% static 'base/darkmode_vars.css' %}" />
    {% elif not users_settings.darkmode and users_settings.high_contrast %}
    <link rel="stylesheet" href="{% static 'base/lightmode_contrast_vars.css' %}" />
    {% elif not users_settings.darkmode and not users_settings.high_contrast %}
    <link rel="stylesheet" href="{% static 'base/lightmode_vars.css' %}" />
    {% else %}
    <link rel="stylesheet" href="{% static 'base/darkmode_vars.css' %}" />
    {% endif %}
    <link rel="stylesheet" href="{% static 'base/styles.css' %}" />
  </head>
  <body>
    <div class="container">{% block content %} {% endblock content %}</div>
    {% if display_settings %}
    <div class="container">
      <header>
        <h2 style="font-size: 24px">Settings</h2>
      </header>
      <div class="settings">
        <a href="{% url 'hide_completed' %}">
          {% if users_settings.hide_completed %}
          <div class="task-complete-icon"></div>
          {% else %}
          <div class="task-incomplete-icon"></div>
          {% endif %}
          <div style="padding-left: 8px">hide completed</div>
        </a>
        <div>
          <a href="{% url 'filter_by_deadline' %}">
            {% if users_settings.filter_by_deadline %}
            <div class="task-complete-icon"></div>
            {% else %}
            <div class="task-incomplete-icon"></div>
            {% endif %}
          </a>
          <a class="text" href="{% url 'filter_by_deadline' %}" style="padding-left: 8px"
            >hide tasks with deadline before:&nbsp</a
          >
          <a class='text' href="{% url 'users_display_after_date' users_settings.id %}"><u>{{users_settings.users_display_after_date|date:"Y-m-d"}}</u></a>
          
          {% comment %} <a href="{% url 'users_display_after_date' users_settings.id %}"><input class="button" style='position: relative; top: -5px; left: 10px; padding: 7px;' type='button' value='change'></input></a> {% endcomment %}
        </div>
        <a href="{% url 'theme' %}">
          {% if users_settings.darkmode %}
          <div class="task-complete-icon"></div>
          {% else %}
          <div class="task-incomplete-icon"></div>
          {% endif %}
          <div style="padding-left: 8px">dark mode</div>
        </a>
        <a href="{% url 'contrast' %}">
          {% if users_settings.high_contrast %}
          <div class="task-complete-icon"></div>
          {% else %}
          <div class="task-incomplete-icon"></div>
          {% endif %}
          <div style="padding-left: 8px">high contrast mode</div>
        </a>
      </div>
    </div>
    {% endif %}

    {% if not hide_footer %}
    <div class='container'>
      <footer>
        <h1><a href="{% url 'readme' %}" style='text-decoration: underline;'>Readme</a></h1>
          
      </footer>
    </div>
    {% endif %}
  </body>
</html>

base/templates/base/readme.html
{% extends 'base/main.html' %}
<!-- displaying the view as content of base/main.html -->
{% block content %}
<!-- content -->
{% load static %}

<header>
  <h2 style="font-size: 2.4rem">README</h2>
  <a href="{% url 'tasks' %}">&#8592; back</a>
</header>

{% comment %}
<!--

TO UPDATE THIS PAGE:

1. put readme.md into https://markdowntohtml.com

2. in resulting raw html, replace all:

FROM: img src="base/static/
INTO: img class="screenshot" src="{% static '

FROM: .png"
INTO: .png' %}" 

3. paste into:
<div id="readme">RESULT</div>{% endblock content %}

-->
{% endcomment %}

<div id="readme">
  <h1 id="basic-commands">Basic commands</h1>
  <h3 id="starting-the-project-as-a-development-server-">Starting the project as a development server:</h3>
  <ol>
    <li>
      Create a python environment with python and Django:
      <ul>
        <li>python 3.8.15 + Django 4.1.4 - version used for development</li>
        <li>python 3.11.1 + Django 4.1.5 - the newest versions the project was tested on</li>
      </ul>
    </li>
    <li>Download and open project files within the environment</li>
    <li>in cmd, run: <code>python manage.py migrate</code></li>
    <li>
      in cmd, run: <code>python manage.py runserver</code>
      <blockquote>
        <p>The server should now be running on 127.0.0.1:8000</p>
      </blockquote>
    </li>
  </ol>
  <h3 id="creating-a-super-user-and-opening-administration-panel-">Creating a super user and opening administration panel:</h3>
  <ol>
    <li>in cmd, run: python manage.py createsuperuser</li>
    <li>enter user data according to prompts</li>
    <li>run server with python manage.py runserver</li>
    <li>
      The administration panel located on 127.0.0.1:8000/admin should now allow access after logging in with previously entered data.
      <blockquote>
        <p>
          <strong>Please note</strong> that this user is created for administrative purposes and won&#39;t be properly initialized for using
          &quot;standard&quot;, non-administrative features of the app. It can hovewer be changed by creating UsersSettings for the superuser account.
        </p>
      </blockquote>
    </li>
  </ol>
  <h3 id="running-project-after-initial-setup-">Running project after initial setup:</h3>
  <pre><code>python manage<span class="hljs-selector-class">.py</span> runserver
</code></pre>
  <h3 id="setting-up-migrations-after-changes-in-models-">Setting up migrations after changes in models:</h3>
  <pre><code>python manage<span class="hljs-selector-class">.py</span> makemigrations
python manage<span class="hljs-selector-class">.py</span> migrate
</code></pre>
  <h1 id="design-features-and-details">Design, features and details</h1>
  <h3 id="nonexhaustive-list-of-features-">Nonexhaustive list of features:</h3>
  <ul>
    <li>user registration and authorization based on Django&#39;s built-in solutions</li>
    <li>
      tasks stored in database
      <ul>
        <li>tasks can be created by any user, and are &quot;owned&quot; and only visible to their creator</li>
        <li>all CRUD actions are available to the task&#39;s creator</li>
        <li>users have no access to tasks they didn&#39;t create (403 Forbidden)</li>
      </ul>
    </li>
    <li>
      settings stored in database, allowing for:
      <ul>
        <li>changing graphical themes (by adding different files with CSS variables to pages sent to browser)</li>
        <li>filtering completed tasks</li>
        <li>filtering tasks having deadline before any given date</li>
      </ul>
    </li>
  </ul>
  <h3 id="data-is-stored-using-3-models-classes-defining-data-stored-in-db-">Data is stored using 3 models (classes defining data stored in DB):</h3>
  <ul>
    <li>User - Django&#39;s built-in user model user for authentication</li>
    <li>
      Task - task model containing various data about tasks:
      <ul>
        <li>user - foreign key of user that created and &quot;owns&quot; the task</li>
        <li>title - title of the task</li>
        <li>description - (optional) text field user for storing any additional text data about the task</li>
        <li>complete - boolean field, can be used for task filtering</li>
        <li>deadline - (optional) deadline date that can be later used for task filtering</li>
        <li>created - automatically filled date of task creation</li>
      </ul>
    </li>
    <li>
      UsersSettings
      <ul>
        <li>user - foreign key of user whose settings are being stored in the object</li>
        <li>darkmode - boolean field for switching between light and dark themes</li>
        <li>hide_complete - boolean field for hiding tasks with True in &quot;complete&quot; field</li>
        <li>high_contrast - boolean field for switching between normal- and high-contrast themes</li>
        <li>filter_by_deadline - boolean field for turning task filtration by deadline on/off</li>
        <li>
          users_display_after_day - datetime field based on which the task-by-deadline filtration takes place when filter_by_deadline is set to True
        </li>
      </ul>
    </li>
  </ul>
  <h3 id="file-structure">File structure</h3>
  <pre><code class="lang-py">├─ <span class="hljs-keyword">base</span>        <span class="hljs-meta"># core of Django app (module)</span>
│    ├─ migrations     <span class="hljs-meta"># database migrations</span>
│    ├─ <span class="hljs-keyword">static</span>/<span class="hljs-keyword">base</span>    <span class="hljs-meta"># favicon, screenshots and CSS</span>
│    ├─ templates/<span class="hljs-keyword">base</span> <span class="hljs-meta"># templates for rendering</span>
│    ├─ admin.py       <span class="hljs-meta"># adds models to admin panel</span>
│    ├─ models.py      <span class="hljs-meta"># definitions of models</span>
│    ├─ urls.py        <span class="hljs-meta"># app-wide URL path management</span>
│    ├─ views.py       <span class="hljs-meta"># logic used by URL paths</span>
│    └─ ...            <span class="hljs-meta"># various Django app files</span>
├─ todo_list   <span class="hljs-meta"># core of Django project</span>
│    ├─ settings.py    <span class="hljs-meta"># project's settings</span>
│    ├─ urls.py        <span class="hljs-meta"># URL path management</span>
│    └─ ...            <span class="hljs-meta"># various Django project files</span>
├─ .gitattributes
├─ .gitignore
├─ db.sqlite3  <span class="hljs-meta"># embedded SQLite database</span>
├─ manage.py   <span class="hljs-meta"># Django’s command-<span class="hljs-meta-keyword">line</span> utilities</span>
└─ readme.md
</code></pre>
  <h1 id="examples-screenshots-with-hovertext-">Examples (screenshots with hovertext)</h1>
  <h3 id="adding-new-task">Adding new task</h3>
  <p>
    <img class="screenshot" src="{% static 'base/screenshots/task_deletion2.png' %}" alt="before task creation" title="before task creation" />
    <img class="screenshot" src="{% static 'base/screenshots/add_new_task.png' %}" alt="task creation form" title="task creation form" />
    <img class="screenshot" src="{% static 'base/screenshots/add_new_task2.png' %}" alt="task creation result" title="task creation result" />
  </p>
  <h3 id="task-deletion">Task deletion</h3>
  <p>
    <img class="screenshot" src="{% static 'base/screenshots/add_new_task2.png' %}" alt="before task deletion" title="before task deletion" />
    <img class="screenshot" src="{% static 'base/screenshots/task_deletion.png' %}" alt="task deletion screen" title="task deletion screen" />
    <img class="screenshot" src="{% static 'base/screenshots/task_deletion2.png' %}" alt="task deletion result" title="task deletion result" />
  </p>
  <h3 id="themes">Themes</h3>
  <p>
    <img
      class="screenshot"
      src="{% static 'base/screenshots/dark_contrast.png' %}"
      alt="dark theme with high contrast"
      title="dark theme with high contrast"
    />
    <img class="screenshot" src="{% static 'base/screenshots/dark.png' %}" alt="dark theme" title="dark theme" />
    <img class="screenshot" src="{% static 'base/screenshots/light.png' %}" alt="light theme" title="light theme" />
    <img
      class="screenshot"
      src="{% static 'base/screenshots/light_contrast.png' %}"
      alt="light theme with high contrast"
      title="light theme with high contrast"
    />
  </p>
  <h3 id="hiding-by-deadline">Hiding by deadline</h3>
  <p>
    <img
      class="screenshot"
      src="{% static 'base/screenshots/dark_contrast.png' %}"
      alt="before filtering by deadline"
      title="before filtering by deadline"
    />
    <img
      class="screenshot"
      src="{% static 'base/screenshots/hide_by_deadline0.png' %}"
      alt="setting deadline filter"
      title="setting deadline filter"
    />
    <img
      class="screenshot"
      src="{% static 'base/screenshots/hide_completed_1.png' %}"
      alt="after setting filter but before activation"
      title="after setting filter but before activation"
    />
    <img
      class="screenshot"
      src="{% static 'base/screenshots/hide_by_deadline.png' %}"
      alt="deadline filtering result"
      title="deadline filtering result"
    />
  </p>
  <h3 id="hiding-completed">Hiding completed</h3>
  <p>
    <img class="screenshot" src="{% static 'base/screenshots/hide_completed_1.png' %}" alt="before hiding" title="before hiding" />
    <img class="screenshot" src="{% static 'base/screenshots/hide_completed_2.png' %}" alt="after hiding" title="after hiding" />
  </p>
  <h3 id="login-client-side-validation">Login client-side validation</h3>
  <p>
    <img
      class="screenshot"
      src="{% static 'base/screenshots/login_validation.png' %}"
      alt="login client-side validation - no password"
      title="login client-side validation - no password"
    />
  </p>
  <h3 id="registration-client-side-validation">Registration client-side validation</h3>
  <p>
    <img
      class="screenshot"
      src="{% static 'base/screenshots/register_validation1.png' %}"
      alt="registration client-side validation - too short password"
      title="registration client-side validation - too short password"
    />
    <img
      class="screenshot"
      src="{% static 'base/screenshots/register_validation2.png' %}"
      alt="registration client-side validation - digits-only password"
      title="registration client-side validation - digits-only password"
    />
  </p>
  <h3 id="filtering-task-by-title">Filtering task by title</h3>
  <p>
    <img class="screenshot" src="{% static 'base/screenshots/text%20filtering.png' %}" alt="before filtering" title="before filtering" />
    <img class="screenshot" src="{% static 'base/screenshots/text%20filtering2.png' %}" alt="after filtering" title="after filtering" />
  </p>
  <h3 id="updating-an-existing-task">Updating an existing task</h3>
  <p>
    <img class="screenshot" src="{% static 'base/screenshots/task_deletion2.png' %}" alt="before updating" title="before updating" />
    <img class="screenshot" src="{% static 'base/screenshots/update_task.png' %}" alt="updating form - initial" title="updating form - initial" />
    <img
      class="screenshot"
      src="{% static 'base/screenshots/update_task_2.png' %}"
      alt="updating form - with changes"
      title="updating form - with changes"
    />
    <img class="screenshot" src="{% static 'base/screenshots/update_task_3.png' %}" alt="result of updating" title="result of updating" />
  </p>
  <h3 id="normal-and-dense-layout">Normal and dense layout</h3>
  <p>
    <img class="screenshot" src="{% static 'base/screenshots/normal_layout.png' %}" alt="Normal layout" title="Normal layout" />
    <img class="screenshot" src="{% static 'base/screenshots/dense_layout.png' %}" alt="Dense layout" title="Dense layout" />
  </p>
</div>
{% endblock content %}

base/templates/base/task.html
{% extends 'base/main.html' %}
<!-- displaying the view as content of base/main.html -->
{% block content %}
<!-- content -->

<h1>Task: {{task}}</h1>

{% endblock content %}

base/templates/base/task_confirm_delete.html
{% extends 'base/main.html' %}
<!-- displaying the view as content of base/main.html -->
{% block content %}
<!-- content -->

<header>
  <div>
    <h1>Delete task</h1>
  </div>
  <a href="{% url 'tasks' %}">&#8592; back</a>
</header>
<div class="card-body-as-p text">
  <form method="POST">
    {% csrf_token %}
    <p>Are you sure you want to delete the "{{task}}" task?</p>
    <input class="button" type="submit" value="Delete" />
    <a href="{% url 'tasks' %}"><input class="button" type="button" value="Cancel" /></a>
  </form>
</div>

{% endblock content %}

base/templates/base/task_detail.html
<h1>Task: {{task}}</h1>

base/templates/base/task_form.html
{% extends 'base/main.html' %}
<!-- displaying the view as content of base/main.html -->
{% block content %}
<!-- content -->

<!-- <header>
  <a href="{% url 'tasks' %}">&#8592; back</a>
</header> -->

<header>
  <div>
    {% if task.title %}
    <h1>Update task "{{task.title}}"</h1>
    {% else %}
    <h1>Add new task</h1>
    {% endif %}
  </div>
  <a href="{% url 'tasks' %}">&#8592; back</a>
</header>

<div class="card-body-as-p">
  <form method="POST" action="">
    {% csrf_token %}
    <!-- ^ against c-s req forgery-->
    <div class="text">
      <p>
        <label for="id_title">Title:</label>
        <input type="text" name="title" value="{{task.title}}" maxlength="200" required="" id="id_title" />
      </p>
      <p>
        <label for="id_description">Description:</label>
        <textarea name="description" cols="40" rows="5" id="id_description">{{task.description}}</textarea>
      </p>
      <p>
        <label for="id_complete">Complete:</label>
        {% if task.complete %}
        <input type="checkbox" name="complete" id="id_complete" checked />
        {% else %}
        <input type="checkbox" name="complete" id="id_complete" />
        {% endif %}
      </p>
      <p>
        <label for="id_deadline">Deadline:</label>
        <input type="date" name="deadline" value="{{task.deadline}}" id="id_deadline" />
      </p>
    </div>
    <input class="button" type="submit" value="Submit" />
    <a href="{% url 'tasks' %}"><input class="button" type='button' value='Cancel'></input></a>
  </form>
</div>

{% endblock content %}

base/templates/base/userssettings_form.html
{% extends 'base/main.html' %}
<!-- displaying the view as content of base/main.html -->
{% block content %}
<!-- content -->

<!-- <header>
  <a href="{% url 'tasks' %}">&#8592; back</a>
</header> -->

<header>
  <div>
    <h1>Modify setting</h1>
  </div>
  <a href="{% url 'tasks' %}">&#8592; back</a>
</header>

<div class="card-body-as-p text">
  <form method="POST" action="">
    {% csrf_token %}
    <!-- ^ against c-s req forgery-->
    {% comment %}
    <div class="text">{{form.as_p}}</div>
    {% endcomment %}
    <p>
      <label style="margin-top: 10px">
        {% comment %} {{form.users_display_after_date.label}} {% endcomment %} Hide tasks with deadline before :</label
      >
      {% comment %} {{form.users_display_after_date}} {% endcomment %}
      <input type="date" name="users_display_after_date" value="{{userssettings.users_display_after_date}}" id="id_users_display_after_date" />
    </p>
    <input class="button" type="submit" value="Submit" />
    <a class="button" href="{% url 'tasks' %}">Cancel</a>
  </form>
</div>

{% endblock content %}